function comparisonResults = comparePlanningAlgorithms( ...
    environment,occupancyGrid,startPoint,goalPoint, ...
    astarRawPath,astarPlanningInfo,astarPlanningTime, ...
    astarSearchHistory,cfg)
%COMPAREPLANNINGALGORITHMS Compare five planners fairly and animate them.
%
% A single clicked goal is reused for every planner. All planners share
% the same start point, goal point, inflated occupancy grid, and world.

plannerNames = {'A*','Dijkstra','RRT','RRT*','PRM'};
numberOfPlanners = numel(plannerNames);
comparisonResults = repmat(struct( ...
    'name','', ...
    'success',false, ...
    'rawPath',zeros(0,2), ...
    'displayPath',zeros(0,2), ...
    'planningTime',inf, ...
    'pathLength',inf, ...
    'searchNodes',0, ...
    'animationHistory',struct()),numberOfPlanners,1);

comparisonResults(1).name = 'A*';
comparisonResults(1).success = astarPlanningInfo.success;
comparisonResults(1).rawPath = astarRawPath;
comparisonResults(1).planningTime = astarPlanningTime;
comparisonResults(1).searchNodes = astarPlanningInfo.expandedNodes;
astarSearchHistory.type = 'grid';
astarSearchHistory.count = size(astarSearchHistory.expandedWorld,1);
comparisonResults(1).animationHistory = astarSearchHistory;

if astarPlanningInfo.success && ~isempty(astarRawPath)
    comparisonResults(1).displayPath = postProcessPath( ...
        astarRawPath,occupancyGrid,cfg);
    comparisonResults(1).pathLength = pathLengthLocal( ...
        comparisonResults(1).displayPath);
end

comparisonResults(2).name = 'Dijkstra';
plannerTimer = tic;
[dijkstraPath,dijkstraInfo,dijkstraHistory] = planPathDijkstra( ...
    occupancyGrid,startPoint,goalPoint);
comparisonResults(2).planningTime = toc(plannerTimer);
comparisonResults(2).success = dijkstraInfo.success;
comparisonResults(2).rawPath = dijkstraPath;
comparisonResults(2).searchNodes = dijkstraInfo.expandedNodes;
comparisonResults(2).animationHistory = dijkstraHistory;
if dijkstraInfo.success && ~isempty(dijkstraPath)
    comparisonResults(2).displayPath = postProcessPath( ...
        dijkstraPath,occupancyGrid,cfg);
    comparisonResults(2).pathLength = pathLengthLocal( ...
        comparisonResults(2).displayPath);
end

rng(cfg.environment.randomSeed+101,'twister');
comparisonResults(3).name = 'RRT';
plannerTimer = tic;
[rrtPath,rrtInfo,rrtHistory] = planPathRRT( ...
    occupancyGrid,startPoint,goalPoint,cfg);
comparisonResults(3).planningTime = toc(plannerTimer);
comparisonResults(3).success = rrtInfo.success;
comparisonResults(3).rawPath = rrtPath;
comparisonResults(3).searchNodes = rrtInfo.nodeCount;
comparisonResults(3).animationHistory = rrtHistory;
if rrtInfo.success && ~isempty(rrtPath)
    comparisonResults(3).displayPath = postProcessPath( ...
        rrtPath,occupancyGrid,cfg);
    comparisonResults(3).pathLength = pathLengthLocal( ...
        comparisonResults(3).displayPath);
end

rng(cfg.environment.randomSeed+202,'twister');
comparisonResults(4).name = 'RRT*';
plannerTimer = tic;
[rrtStarPath,rrtStarInfo,rrtStarHistory] = planPathRRTStar( ...
    occupancyGrid,startPoint,goalPoint,cfg);
comparisonResults(4).planningTime = toc(plannerTimer);
comparisonResults(4).success = rrtStarInfo.success;
comparisonResults(4).rawPath = rrtStarPath;
comparisonResults(4).searchNodes = rrtStarInfo.nodeCount;
comparisonResults(4).animationHistory = rrtStarHistory;
if rrtStarInfo.success && ~isempty(rrtStarPath)
    comparisonResults(4).displayPath = postProcessPath( ...
        rrtStarPath,occupancyGrid,cfg);
    comparisonResults(4).pathLength = pathLengthLocal( ...
        comparisonResults(4).displayPath);
end

rng(cfg.environment.randomSeed+303,'twister');
comparisonResults(5).name = 'PRM';
plannerTimer = tic;
[prmPath,prmInfo,prmHistory] = planPathPRM( ...
    occupancyGrid,startPoint,goalPoint,cfg);
comparisonResults(5).planningTime = toc(plannerTimer);
comparisonResults(5).success = prmInfo.success;
comparisonResults(5).rawPath = prmPath;
comparisonResults(5).searchNodes = prmInfo.nodeCount;
comparisonResults(5).animationHistory = prmHistory;
if prmInfo.success && ~isempty(prmPath)
    comparisonResults(5).displayPath = postProcessPath( ...
        prmPath,occupancyGrid,cfg);
    comparisonResults(5).pathLength = pathLengthLocal( ...
        comparisonResults(5).displayPath);
end

% Restore the main project random stream after planner comparisons.
rng(cfg.environment.randomSeed,'twister');

animatePlanningAlgorithms( ...
    environment,startPoint,goalPoint,comparisonResults,cfg);

createComparisonFigureLocal( ...
    environment,startPoint,goalPoint,comparisonResults,cfg);

if cfg.compare.navigation.enabled
    animateMultiRobotNavigation( ...
        environment,startPoint,goalPoint,comparisonResults,cfg);
end

Algorithm = {comparisonResults.name}';
Success = [comparisonResults.success]';
PlanningTime_s = [comparisonResults.planningTime]';
DisplayedPathLength_m = [comparisonResults.pathLength]';
SearchNodes = [comparisonResults.searchNodes]';
summaryTable = table(Algorithm,Success,PlanningTime_s, ...
    DisplayedPathLength_m,SearchNodes);

writetable(summaryTable,fullfile( ...
    cfg.output.resultsFolder, ...
    'planning_algorithm_comparison_metrics.csv'));
end

function lengthValue = pathLengthLocal(pathData)
if size(pathData,1) < 2
    lengthValue = 0;
else
    lengthValue = sum(sqrt(sum(diff(pathData,1,1).^2,2)));
end
end

function createComparisonFigureLocal( ...
    environment,startPoint,goalPoint,comparisonResults,cfg)

comparisonFigure = figure( ...
    'Color','w', ...
    'Position',[35 35 1680 930], ...
    'Name','Planning Algorithm Comparison', ...
    'NumberTitle','off');

if exist('tiledlayout','file') == 2 || exist('tiledlayout','builtin') == 5
    tileLayout = tiledlayout(comparisonFigure,2,3, ...
        'TileSpacing','compact','Padding','compact');
    title(tileLayout, ...
        'A*, Dijkstra, RRT, RRT*, and PRM — Same Start, Goal, and Environment', ...
        'FontWeight','bold','FontSize',14);

    axesList = gobjects(6,1);
    for index = 1:6
        axesList(index) = nexttile(tileLayout,index);
    end
else
    axesList = gobjects(6,1);
    positions = [ ...
        0.04 0.54 0.29 0.38; ...
        0.355 0.54 0.29 0.38; ...
        0.67 0.54 0.29 0.38; ...
        0.04 0.08 0.29 0.38; ...
        0.355 0.08 0.29 0.38; ...
        0.67 0.08 0.29 0.38];
    for index = 1:6
        axesList(index) = axes('Parent',comparisonFigure, ...
            'Position',positions(index,:));
    end
end

for plannerIndex = 1:numel(comparisonResults)
    axesHandle = axesList(plannerIndex);
    plotEnvironment(axesHandle,environment,cfg);
    hold(axesHandle,'on');

    plot(axesHandle,startPoint(1),startPoint(2), ...
        'gs','MarkerFaceColor','g','MarkerSize',8);
    plot(axesHandle,goalPoint(1),goalPoint(2), ...
        'r*','MarkerSize',16,'LineWidth',2);

    result = comparisonResults(plannerIndex);

    if result.success && ~isempty(result.displayPath)
        plot(axesHandle,result.displayPath(:,1),result.displayPath(:,2), ...
            '-','Color',[0.10 0.35 0.95],'LineWidth',2.0);

        statusText = sprintf( ...
            'Success\nTime: %.3f s\nPath: %.2f m\nNodes: %d', ...
            result.planningTime,result.pathLength,result.searchNodes);
        statusColor = [0.00 0.38 0.08];
    else
        statusText = sprintf( ...
            'No path found\nTime: %.3f s\nNodes: %d', ...
            result.planningTime,result.searchNodes);
        statusColor = [0.78 0.10 0.10];
    end

    title(axesHandle,result.name,'FontWeight','bold','FontSize',12);
    text(axesHandle,0.02,0.98,statusText, ...
        'Units','normalized','HorizontalAlignment','left', ...
        'VerticalAlignment','top','BackgroundColor','w', ...
        'Margin',4,'FontWeight','bold','Color',statusColor, ...
        'FontSize',9);
end

summaryAxes = axesList(6);
axis(summaryAxes,[0 1 0 1]);
axis(summaryAxes,'off');
box(summaryAxes,'on');

summaryLines = { ...
    'COMPARISON SUMMARY'; ...
    sprintf('Start: (%.2f, %.2f) m',startPoint(1),startPoint(2)); ...
    sprintf('Goal:  (%.2f, %.2f) m',goalPoint(1),goalPoint(2)); ...
    ' '; ...
    'All planners use the same:'; ...
    '- environment'; ...
    '- occupancy grid'; ...
    '- start point'; ...
    '- clicked goal'; ...
    ' '; ...
    'Blue = final planned route'};

text(summaryAxes,0.04,0.96,strjoin(summaryLines,newline), ...
    'VerticalAlignment','top','FontSize',10, ...
    'FontWeight','bold','Interpreter','none');

hideAxesToolbars(comparisonFigure);

print(comparisonFigure,fullfile( ...
    cfg.output.resultsFolder,'planning_algorithm_comparison.png'), ...
    '-dpng','-r180');
end
