function exportFiveSlamMaps( ...
    navigationResults,startPoint,goalPoint,cfg)
%EXPORTFIVESLAMMAPS Export the five final live occupancy maps together.
%
% Output:
%   results/slam_live_occupancy_map.png
%
% Each panel uses the final SLAM state belonging to one independent
% A*, Dijkstra, RRT, RRT*, or PRM robot.

if isempty(navigationResults)
    warning('No navigation results were available for SLAM export.');
    return;
end

algorithmNames = {navigationResults.name};
preferredOrder = {'A*','Dijkstra','RRT','RRT*','PRM'};
displayOrder = zeros(1,numel(preferredOrder));

for index = 1:numel(preferredOrder)
    matchIndex = find(strcmp( ...
        algorithmNames,preferredOrder{index}),1);

    if isempty(matchIndex)
        displayOrder(index) = index;
    else
        displayOrder(index) = matchIndex;
    end
end

figureHandle = figure( ...
    'Color','w', ...
    'Position',[40 40 1650 900], ...
    'Name','Five SLAM Live Occupancy Maps', ...
    'NumberTitle','off');

useTiledLayout = ...
    exist('tiledlayout','file') == 2 || ...
    exist('tiledlayout','builtin') == 5;

if useTiledLayout
    layoutHandle = tiledlayout( ...
        figureHandle,2,3, ...
        'TileSpacing','compact', ...
        'Padding','compact');

    title(layoutHandle, ...
        ['SLAM Live Occupancy Map Comparison — ' ...
         'A*, Dijkstra, RRT, RRT*, and PRM'], ...
        'FontWeight','bold', ...
        'FontSize',15);

    axesHandles = gobjects(6,1);

    for tileIndex = 1:6
        axesHandles(tileIndex) = nexttile( ...
            layoutHandle,tileIndex);
    end
else
    axesHandles = gobjects(6,1);

    positions = [ ...
        0.045 0.555 0.285 0.370; ...
        0.357 0.555 0.285 0.370; ...
        0.669 0.555 0.285 0.370; ...
        0.200 0.085 0.285 0.370; ...
        0.515 0.085 0.285 0.370; ...
        0.825 0.085 0.130 0.370];

    for tileIndex = 1:6
        axesHandles(tileIndex) = axes( ...
            'Parent',figureHandle, ...
            'Position',positions(tileIndex,:));
    end
end

for panelIndex = 1:5
    resultIndex = displayOrder(panelIndex);
    state = navigationResults(resultIndex);
    axesHandle = axesHandles(panelIndex);

    mapRgb = occupancyRgbLocal(state.slamState);

    image(axesHandle, ...
        [0 cfg.environment.worldWidth], ...
        [0 cfg.environment.worldHeight], ...
        mapRgb);

    set(axesHandle, ...
        'YDir','normal', ...
        'FontSize',9, ...
        'LineWidth',1.0, ...
        'Layer','top');

    axis(axesHandle,'equal');
    axis(axesHandle,[ ...
        0 cfg.environment.worldWidth ...
        0 cfg.environment.worldHeight]);

    hold(axesHandle,'on');
    grid(axesHandle,'on');
    box(axesHandle,'on');
    set(axesHandle,'GridAlpha',0.10);

    trajectory = state.history( ...
        1:state.historyCount,1:2);

    plot(axesHandle, ...
        trajectory(:,1),trajectory(:,2), ...
        '-','Color',[0.86 0.08 0.08], ...
        'LineWidth',1.6);

    plot(axesHandle, ...
        startPoint(1),startPoint(2), ...
        'gs','MarkerFaceColor','g', ...
        'MarkerSize',7,'LineWidth',1.1);

    plot(axesHandle, ...
        goalPoint(1),goalPoint(2), ...
        'r*','MarkerSize',13, ...
        'LineWidth',1.6);

    plot(axesHandle, ...
        state.pose(1),state.pose(2), ...
        'o','Color',[0.05 0.20 0.70], ...
        'MarkerFaceColor',[0.10 0.70 0.95], ...
        'MarkerSize',6,'LineWidth',1.0);

    title(axesHandle,sprintf( ...
        '%s — Explored %.1f%%', ...
        state.name, ...
        100*state.slamState.exploredFraction), ...
        'FontWeight','bold', ...
        'FontSize',11, ...
        'Interpreter','none');

    xlabel(axesHandle,'X position (m)');
    ylabel(axesHandle,'Y position (m)');
end

summaryAxes = axesHandles(6);
axis(summaryAxes,[0 1 0 1]);
axis(summaryAxes,'off');
box(summaryAxes,'on');
hold(summaryAxes,'on');

text(summaryAxes,0.05,0.94, ...
    'SLAM MAP LEGEND', ...
    'FontWeight','bold', ...
    'FontSize',12, ...
    'VerticalAlignment','top');

legendText = sprintf([ ...
    'White: observed free space\n' ...
    'Black: occupied space\n' ...
    'Gray: unexplored space\n' ...
    'Red line: actual robot trajectory\n' ...
    'Green square: shared start\n' ...
    'Red star: shared goal\n' ...
    'Blue circle: final robot pose\n\n' ...
    'All five maps use the same:\n' ...
    '- environment\n' ...
    '- start position\n' ...
    '- clicked goal\n' ...
    '- LiDAR model\n' ...
    '- SLAM settings']);

text(summaryAxes,0.05,0.84,legendText, ...
    'FontSize',10, ...
    'VerticalAlignment','top', ...
    'Interpreter','none');

hideAxesToolbars(figureHandle);
drawnow;

print(figureHandle,fullfile( ...
    cfg.output.resultsFolder, ...
    'slam_live_occupancy_map.png'), ...
    '-dpng','-r200');
end

function mapRgb = occupancyRgbLocal(slamState)
%OCCUPANCYRGBLOCAL Create a crisp grayscale occupancy display.

probability = slamState.probability;
observedMask = slamState.observed;

grayImage = 0.78*ones(size(probability));

freeMask = observedMask & ...
    probability <= 0.40;

occupiedMask = observedMask & ...
    probability >= 0.60;

transitionMask = observedMask & ...
    ~(freeMask | occupiedMask);

grayImage(freeMask) = 0.98;
grayImage(occupiedMask) = 0.03;

if any(transitionMask(:))
    transitionValues = ...
        0.55-0.35*(probability(transitionMask)-0.5);

    grayImage(transitionMask) = min(max( ...
        transitionValues,0.18),0.82);
end

mapRgb = repmat(grayImage,[1 1 3]);
end
